package com.mikaelr.textgameapp;

public enum ItemType {

    NOTHING, SHORT_SWORD, BATTLE_AXE, CHAINMAIL_ARMOR, KNIGHT_ARMOR, LIGHTNING_BOLT, HEALING_SPELL, HEALING_POTION, MANA_POTION, SILVER, GOLD;

}
